[pytest]
pythonpath = .
testpaths = tests
junit_family = xunit1
addopts = --cov=radspion --cov-fail-under 90 --cov-report=html --cov-report=term-missing --ignore=tests/acceptance

# Suppress ResourceWarnings from pytest-cov's internal SQLite usage.
filterwarnings =
    ignore::ResourceWarning
