"""Tests for storyline pack loading and seed_storyline CLI."""

from pathlib import Path

import pytest

from radspion.mission_files import MissionFilesError
from radspion.storyline_pack import StorylineError, generate_sql, load_pack
from radspion.tools.seed_storyline import (
    main,
    resolve_pack_root,
    seed_storyline,
)
from tests.helpers import load_schema_only, write_minimal_pack


def test_load_pack_validates_collapsible_markdown(tmp_path: Path):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    (pack_root / "alpha" / "brief.md").write_text(
        "## Outer ???\n\n### Inner ???\n\nNope.\n",
        encoding="utf-8",
    )
    with pytest.raises(StorylineError, match="nested inside"):
        load_pack(pack_root)


def test_generate_sql_includes_markdown(tmp_path: Path):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    pack = load_pack(pack_root)
    sql = generate_sql(pack)
    assert "INSERT INTO missions" in sql
    assert "## Brief" in sql
    assert "Generated by seed_storyline" in sql


def test_resolve_pack_root_accepts_absolute_path(tmp_path: Path):
    pack_root = tmp_path / "orientation"
    write_minimal_pack(pack_root)
    assert resolve_pack_root(str(pack_root)) == pack_root.resolve()


def test_resolve_pack_root_accepts_pack_name_under_missions_root(tmp_path: Path):
    missions_root = tmp_path / "missions"
    pack_root = missions_root / "orientation"
    write_minimal_pack(pack_root)
    resolved = resolve_pack_root("orientation", missions_root_loader=lambda: missions_root)
    assert resolved == pack_root.resolve()


def test_resolve_pack_root_rejects_missing_pack_name(tmp_path: Path):
    missions_root = tmp_path / "missions"
    missions_root.mkdir()
    with pytest.raises(StorylineError, match="Pack directory not found"):
        resolve_pack_root("missing", missions_root_loader=lambda: missions_root)


def test_resolve_pack_root_rejects_absolute_non_directory(tmp_path: Path):
    missing = tmp_path / "missing-pack"
    with pytest.raises(StorylineError, match="Not a directory"):
        resolve_pack_root(str(missing))


def test_resolve_pack_root_wraps_missions_root_error():
    def broken_loader() -> Path:
        raise MissionFilesError("RADSPION_MISSIONS_ROOT is not set")

    with pytest.raises(StorylineError, match="RADSPION_MISSIONS_ROOT"):
        resolve_pack_root("orientation", missions_root_loader=broken_loader)


def test_seed_storyline_check_only(tmp_path: Path):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    result = seed_storyline(pack_root, check_only=True)
    assert result.mission_count == 1
    assert result.group == "Test Group"
    assert result.output_path is None
    assert result.database_path is None


def test_seed_storyline_writes_sql(tmp_path: Path):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    result = seed_storyline(pack_root, write_sql=True)
    assert result.output_path == pack_root / "test-pack.sql"
    assert result.output_path.is_file()
    assert "INSERT INTO missions" in result.output_path.read_text(encoding="utf-8")


def test_seed_storyline_loads_database(tmp_path: Path):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    db_path = tmp_path / "radspion.db"
    load_schema_only(db_path)

    result = seed_storyline(
        pack_root,
        database_path_loader=lambda: db_path,
    )
    assert result.database_path == db_path

    import sqlite3

    with sqlite3.connect(db_path) as conn:
        row = conn.execute(
            "SELECT title FROM missions WHERE slug = 'alpha'",
        ).fetchone()
    assert row is not None
    assert row[0] == "Alpha"


def test_main_check_only(tmp_path: Path, capsys: pytest.CaptureFixture[str]):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    with pytest.raises(SystemExit) as exc:
        main([str(pack_root), "--check"])
    assert exc.value.code == 0
    captured = capsys.readouterr()
    assert "OK: 1 missions" in captured.out
    assert "Loaded storyline pack" not in captured.out


def test_main_writes_sql(tmp_path: Path, capsys: pytest.CaptureFixture[str]):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    with pytest.raises(SystemExit) as exc:
        main([str(pack_root), "--write-sql"])
    assert exc.value.code == 0
    captured = capsys.readouterr()
    assert "Wrote" in captured.out
    assert (pack_root / "test-pack.sql").is_file()


def test_main_rejects_check_and_write_sql(tmp_path: Path, capsys: pytest.CaptureFixture[str]):
    pack_root = tmp_path / "test-pack"
    write_minimal_pack(pack_root)
    with pytest.raises(SystemExit) as exc:
        main([str(pack_root), "--check", "--write-sql"])
    assert exc.value.code == 1
    assert "Use either --check or --write-sql" in capsys.readouterr().err


def test_main_reports_storyline_error(tmp_path: Path, capsys: pytest.CaptureFixture[str]):
    with pytest.raises(SystemExit) as exc:
        main([str(tmp_path / "missing-pack")])
    assert exc.value.code == 1
    captured = capsys.readouterr()
    assert "Error:" in captured.err
