"""Plan and report destructive deletion of a storyline (story arc) from the database."""

from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

GENERATOR_DELETE = "delete_storyline"

DELETE_CONFIRM_PROMPT = (
    "This will permanently delete storyline {name!r} and all agent progress on its missions.\n"
    "User accounts and other storylines are not deleted.\n"
    "Type {name!r} to confirm: "
)


@dataclass(frozen=True)
class MissionAgentImpact:
    slug: str
    title: str
    active: int
    completed: int

    @property
    def total_rows(self) -> int:
        return self.active + self.completed


@dataclass(frozen=True)
class StorylineDeleteImpact:
    group_id: int
    group_name: str
    missions: tuple[MissionAgentImpact, ...]
    distinct_agents: int

    @property
    def mission_count(self) -> int:
        return len(self.missions)

    @property
    def total_rows(self) -> int:
        return sum(mission.total_rows for mission in self.missions)

    @property
    def total_active(self) -> int:
        return sum(mission.active for mission in self.missions)

    @property
    def total_completed(self) -> int:
        return sum(mission.completed for mission in self.missions)


class StorylineDeleteError(Exception):
    """Raised when a storyline cannot be loaded or deleted from the database."""


class StorylineDeleteAborted(StorylineDeleteError):
    """Raised when the operator declines a storyline deletion."""


def normalize_group_name(group_name: str) -> str:
    """Trim outer whitespace from a storyline name argument."""
    return group_name.strip()


def load_delete_impact(connection: sqlite3.Connection, group_name: str) -> StorylineDeleteImpact:
    """Load mission and agent-impact data for one storyline group."""
    normalized = normalize_group_name(group_name)
    if not normalized:
        raise StorylineDeleteError("Storyline name must be a non-empty string.")

    group_row = connection.execute(
        "SELECT id, name FROM groups WHERE name = ?",
        (normalized,),
    ).fetchone()
    if group_row is None:
        raise StorylineDeleteError(f"Storyline {normalized!r} is not in the database.")

    group_id = group_row["id"]
    mission_rows = connection.execute(
        """
        SELECT m.slug,
               m.title,
               COALESCE(SUM(CASE WHEN ams.status = 'active' THEN 1 END), 0) AS active,
               COALESCE(SUM(CASE WHEN ams.status = 'completed' THEN 1 END), 0) AS completed
        FROM missions m
        LEFT JOIN agent_mission_status ams ON ams.mission_id = m.id
        WHERE m.group_id = ?
        GROUP BY m.id
        ORDER BY m.slug ASC
        """,
        (group_id,),
    ).fetchall()

    distinct_row = connection.execute(
        """
        SELECT COUNT(DISTINCT ams.user_id) AS distinct_agents
        FROM agent_mission_status ams
        JOIN missions m ON m.id = ams.mission_id
        WHERE m.group_id = ?
        """,
        (group_id,),
    ).fetchone()
    distinct_agents = int(distinct_row["distinct_agents"] or 0)

    missions = tuple(
        MissionAgentImpact(
            slug=row["slug"],
            title=row["title"],
            active=int(row["active"]),
            completed=int(row["completed"]),
        )
        for row in mission_rows
    )

    return StorylineDeleteImpact(
        group_id=group_id,
        group_name=group_row["name"],
        missions=missions,
        distinct_agents=distinct_agents,
    )


def format_delete_report(impact: StorylineDeleteImpact) -> str:
    """Return a human-readable impact report for a storyline deletion."""
    mission_label = "mission" if impact.mission_count == 1 else "missions"
    lines = [
        f"Storyline: {impact.group_name!r} ({impact.mission_count} {mission_label})",
        "",
    ]

    for mission in impact.missions:
        lines.append(
            f"{mission.slug}: {mission.total_rows} agent rows "
            f"({mission.active} active, {mission.completed} completed)",
        )

    lines.append("")
    lines.append(
        "Totals: "
        f"{impact.total_rows} agent rows "
        f"({impact.total_active} active, {impact.total_completed} completed) "
        f"across {impact.distinct_agents} agents",
    )
    return "\n".join(lines)


def delete_sql_path(group_name: str, *, output_dir: Path | None = None) -> Path:
    """Return the default path for a generated delete SQL file."""
    base = output_dir or Path.cwd()
    slug = re.sub(r"[^a-z0-9]+", "-", group_name.lower()).strip("-") or "storyline"
    return base / f"{slug}-delete.sql"


def generate_delete_sql(impact: StorylineDeleteImpact) -> str:
    """Generate DELETE SQL for one storyline group."""
    return f"""-- Generated by {GENERATOR_DELETE} — do not edit by hand.
-- Storyline: {impact.group_name}

PRAGMA foreign_keys = ON;

BEGIN;

DELETE FROM groups WHERE id = {impact.group_id};

COMMIT;
"""


def confirm_delete_group_name(
    group_name: str,
    *,
    auto_yes: bool,
    is_tty: bool,
    prompt_template: str = DELETE_CONFIRM_PROMPT,
) -> bool:
    """Return True when the operator confirmed deletion by typing the group name."""
    if auto_yes:
        return True
    if not is_tty:
        return False
    answer = input(prompt_template.format(name=group_name)).strip()
    return answer == group_name


def delete_storyline_group(connection: sqlite3.Connection, impact: StorylineDeleteImpact) -> None:
    """Delete one storyline group and all cascaded mission data."""
    connection.execute("DELETE FROM groups WHERE id = ?", (impact.group_id,))
