-- Default system seed: Orientation story arc + basic-training (open mission for all signed-in agents).
-- Prerequisite: src/radspion/sql/schema.sql
-- Generated by radspion-missions/scripts/generate_radspion_sql.py — do not edit by hand.

PRAGMA foreign_keys = ON;

BEGIN;

INSERT INTO groups (id, name) VALUES
    (1, 'Orientation');

INSERT INTO missions (id, slug, title, brief_markdown, debrief_markdown, group_id, access_rule, completion_code) VALUES
    (1, 'basic-training', 'Welcome to Radspion', '# Welcome to Radspion — Brief

Placeholder mission content. Replace with operator-authored markdown.

```bash
echo "orientation example"
```

1. Review the briefing, then run:

   ```bash
   echo "step one"
   ```

2. Continue when ready.
', '# Welcome to Radspion — Debrief

Placeholder. Shown after completion only.
', 1, 'open', 'WELCOME-AGENT-OK');

COMMIT;
