-- Testing Storyline seed (dev/test only — not for production).
-- Requires schema.sql, seed_orientation.sql.
-- See docs/design/05-testing-storyline.md
-- Generated by radspion-missions/scripts/generate_radspion_sql.py — do not edit by hand.

PRAGMA foreign_keys = ON;

BEGIN;

INSERT INTO groups (name) VALUES ('Testing Storyline');

INSERT INTO users (id, email, google_subject_id, display_name) VALUES
    (1, 'alice@moravian.edu', 'google-alice', 'Alice'),
    (2, 'bob@moravian.edu', 'google-bob', 'Bob'),
    (3, 'charlie@moravian.edu', 'google-charlie', 'Charlie'),
    (4, 'diana@moravian.edu', 'google-diana', 'Diana');

INSERT INTO missions (slug, title, brief_markdown, debrief_markdown, group_id, access_rule, completion_code) VALUES
    ('es-alpha', 'ES: Alpha', '# ES: Alpha — Brief

## Overview

This is the overview for the mission called ES: Alpha.

## Completion Code

The completion code for this mission is `COMPLETE es-alpha`.
', '# ES: Alpha — Debrief

Congratulations, you completed ES: Alpha.

Completing this mission unlocks ES: Gamma on your dashboard.
', (SELECT id FROM groups WHERE name = 'Testing Storyline'), 'unlock_code', 'COMPLETE es-alpha'),
    ('es-beta', 'ES: Beta', '# ES: Beta — Brief

## Overview

This is the overview for the mission called ES: Beta.

## Completion Code

The completion code for this mission is `COMPLETE es-beta`.

## Hidden Mission

This mission provides the unlock code for another mission: `HIDDEN UNLOCK`.
', '# ES: Beta — Debrief

Congratulations, you completed ES: Beta.

Completing this mission is one of two prerequisites for unlocking ES: Delta (you also need ES: Gamma).
', (SELECT id FROM groups WHERE name = 'Testing Storyline'), 'unlock_code', 'COMPLETE es-beta'),
    ('es-hidden', 'ES: Hidden', '# ES: Hidden — Brief

## Overview

This is the overview for the mission called ES: Hidden.

## Completion Code

The completion code for this mission is `COMPLETE es-hidden`.
', '# ES: Hidden — Debrief

Congratulations, you completed ES: Hidden.

This mission does not unlock any other missions (dead end).
', (SELECT id FROM groups WHERE name = 'Testing Storyline'), 'unlock_code', 'COMPLETE es-hidden'),
    ('es-gamma', 'ES: Gamma', '# ES: Gamma — Brief

## Overview

This is the overview for the mission called ES: Gamma.

## Completion Code

The completion code for this mission is `COMPLETE es-gamma`.
', '# ES: Gamma — Debrief

Congratulations, you completed ES: Gamma.

Completing this mission is one of two prerequisites for unlocking ES: Delta (you also need ES: Beta).
', (SELECT id FROM groups WHERE name = 'Testing Storyline'), 'requires_complete', 'COMPLETE es-gamma'),
    ('es-delta', 'ES: Delta', '# ES: Delta — Brief

## Overview

This is the overview for the mission called ES: Delta.

## Completion Code

The completion code for this mission is `COMPLETE es-delta`.
', '# ES: Delta — Debrief

Congratulations, you completed ES: Delta.

This mission does not unlock any other missions (finale).
', (SELECT id FROM groups WHERE name = 'Testing Storyline'), 'requires_complete', 'COMPLETE es-delta');

INSERT INTO mission_unlock_codes (mission_id, unlock_code)
SELECT id, 'EXAMPLE UNLOCK' FROM missions WHERE slug IN ('es-alpha', 'es-beta');

INSERT INTO mission_unlock_codes (mission_id, unlock_code)
SELECT id, 'HIDDEN UNLOCK' FROM missions WHERE slug = 'es-hidden';

INSERT INTO mission_list_requires (mission_id, required_mission_id)
SELECT child.id, parent.id
FROM missions child
JOIN missions parent ON parent.slug = 'es-alpha'
WHERE child.slug = 'es-gamma';

INSERT INTO mission_list_requires (mission_id, required_mission_id)
SELECT child.id, parent.id
FROM missions child
JOIN missions parent ON parent.slug = 'es-beta'
WHERE child.slug = 'es-delta';

INSERT INTO mission_list_requires (mission_id, required_mission_id)
SELECT child.id, parent.id
FROM missions child
JOIN missions parent ON parent.slug = 'es-gamma'
WHERE child.slug = 'es-delta';

-- Diana: orientation only (no storyline unlocks).
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 4, id, 'active' FROM missions WHERE slug = 'basic-training';

-- Alice: EXAMPLE UNLOCK path — alpha complete, beta active, gamma active.
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 1, id, 'completed' FROM missions WHERE slug = 'basic-training';
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 1, id, 'completed' FROM missions WHERE slug = 'es-alpha';
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 1, id, 'active' FROM missions WHERE slug = 'es-beta';
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 1, id, 'active' FROM missions WHERE slug = 'es-gamma';

-- Charlie: beta complete, alpha still active (gamma and delta not listable).
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 3, id, 'completed' FROM missions WHERE slug = 'basic-training';
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 3, id, 'active' FROM missions WHERE slug = 'es-alpha';
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 3, id, 'completed' FROM missions WHERE slug = 'es-beta';

-- Bob: all storyline missions completed (including hidden dead-end).
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 2, id, 'completed' FROM missions WHERE slug = 'basic-training';
INSERT INTO agent_mission_status (user_id, mission_id, status)
SELECT 2, id, 'completed' FROM missions WHERE slug IN (
    'es-alpha', 'es-beta', 'es-hidden', 'es-gamma', 'es-delta'
);

COMMIT;
