name: Acceptance Tests

on: [push, pull_request]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup repo and environment
        uses: ./.github/actions/setup_venv

      - name: Install Playwright Chromium
        run: .venv/bin/playwright install --with-deps chromium

      - name: Execute acceptance tests
        run: .venv/bin/pytest tests/acceptance --no-cov
